# Generated by Django 5.2.2 on 2025-08-15 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_role_registroponto'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('status_anterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Novo')),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('registro_manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_detalhado', to='core.registromanutencao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Histórico de Manutenção',
                'verbose_name_plural': 'Históricos de Manutenção',
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
