# Generated by Django 5.2.2 on 2025-08-15 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historicomanutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='chefe_de_equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_liderados', to='core.funcionario', verbose_name='Chefe de Equipe'),
        ),
        migrations.AlterField(
            model_name='registromanutencao',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento'),
        ),
        migrations.CreateModel(
            name='ConfirmacaoPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado_pelo_lider', models.BooleanField(default=False, verbose_name='Confirmado pelo Líder')),
                ('confirmado_pelo_membro', models.BooleanField(default=False, verbose_name='Confirmado pelo Membro')),
                ('data_confirmacao_lider', models.DateTimeField(blank=True, null=True)),
                ('data_confirmacao_membro', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes_presenca', to='core.evento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacoes_presenca', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Confirmação de Presença',
                'verbose_name_plural': 'Confirmações de Presença',
                'unique_together': {('evento', 'funcionario')},
            },
        ),
        migrations.DeleteModel(
            name='RegistroPonto',
        ),
    ]
