# Generated by Django 5.2.2 on 2025-08-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_evento_chefe_de_equipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='equipe',
        ),
        migrations.CreateModel(
            name='EscalaFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escala_equipe', to='core.evento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Escala de Funcionário',
                'verbose_name_plural': 'Escalas de Funcionários',
                'unique_together': {('evento', 'funcionario')},
            },
        ),
    ]
