# Generated by Django 5.2.2 on 2025-08-01 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_criado_por_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditivoOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(verbose_name='Descrição do Aditivo')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operacao_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='core.evento')),
            ],
            options={
                'verbose_name': 'Aditivo de Operação',
                'verbose_name_plural': 'Aditivos de Operações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('aditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_aditivo', to='core.aditivooperacao')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipamento')),
            ],
        ),
    ]
