# Generated by Django 5.2.2 on 2025-08-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aditivooperacao_materialaditivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromanutencao',
            name='os_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número da O.S.'),
        ),
    ]
