# Generated by Django 5.2.2 on 2025-08-11 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registromanutencao_os_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('planejamento', 'Planejamento'), ('logistica', 'Logística'), ('manutencao', 'Manutenção'), ('freelancer_ponto', 'Freelancer (Apenas Ponto)')], default='planejamento', max_length=20, verbose_name='Nível de Acesso'),
        ),
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Entrada')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('status', models.CharField(choices=[('PRESENTE', 'Presente'), ('FINALIZADO', 'Finalizado')], default='PRESENTE', max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='core.evento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_ponto', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'ordering': ['-data_hora_entrada'],
            },
        ),
    ]
